package upnvj.berima.v1.ui.common

object AppStrings {
    const val SEARCH_PLACEHOLDER = "Cari layanan..."
    const val SEARCH_HINT = "Ketik untuk mencari layanan."
    const val SEARCH_NO_RESULTS_TITLE = "Tidak ada hasil"
    const val SEARCH_NO_RESULTS_BODY = "Coba kata kunci lain."

    const val SPLASH_TAGLINE = "Tugas Tuntas, Kantong Pas."
    const val SPLASH_FOOTER = "BERIMA · 2026"

    const val NAV_HOME = "Beranda"
    const val NAV_ORDERS = "Pesanan"
    const val NAV_PROFILE = "Profil"

    const val ORDERS_TITLE = "Pesanan"
    const val ORDERS_TAB_BUYER = "Pemesan"
    const val ORDERS_TAB_SELLER = "Penyedia Jasa"
    const val ORDERS_TAB_BUYER_LABEL = "Sebagai Pemesan"
    const val ORDERS_TAB_SELLER_LABEL = "Sebagai Penyedia"

    // Time formatting
    const val TIME_JUST_NOW = "Baru saja"
    const val TIME_MINUTES_AGO_SUFFIX = "m lalu"
    const val TIME_HOURS_AGO_SUFFIX = "j lalu"
    const val TIME_DAYS_AGO_SUFFIX = "h lalu"

    // Order status timeline labels
    const val TIMELINE_CANCELLED = "Dibatalkan"
    const val TIMELINE_REJECTED = "Ditolak"
    const val TIMELINE_PENDING = "Menunggu"
    const val TIMELINE_IN_PROGRESS = "Dikerjakan"
    const val TIMELINE_DELIVERED = "Terkirim"
    const val TIMELINE_REVISION = "Revisi"
    const val TIMELINE_COMPLETED = "Selesai"
    const val TIMELINE_PAID = "Dibayar"

    // Orders list
    const val ORDERS_ROLE_SELLER_PREFIX = "Penyedia Jasa"
    const val ORDERS_ROLE_BUYER_PREFIX = "Pemesan"
    const val ORDERS_EMPTY_TITLE = "Belum ada pesanan"
    const val ORDERS_EMPTY_BODY_BUYER = "Mulai pesan layanan dari teman kampusmu."
    const val ORDERS_EMPTY_BODY_SELLER = "Layanan kamu belum ada yang dipesan."

    // Order detail
    const val ORDER_DETAIL_TITLE = "Detail Pesanan"
    const val ORDER_DETAIL_NOT_FOUND = "Pesanan tidak ditemukan"
    const val ORDER_DETAIL_STATUS_LABEL = "STATUS PESANAN"
    const val ORDER_DETAIL_REQUIREMENT_LABEL = "KEBUTUHAN DARI PEMESAN"
    const val ORDER_DETAIL_NOTE_LABEL = "CATATAN KEBUTUHAN"
    const val ORDER_DETAIL_COUNTERPARTY_SELLER = "PENYEDIA JASA"
    const val ORDER_DETAIL_COUNTERPARTY_BUYER = "PEMESAN"
    const val ORDER_DETAIL_REQUIREMENT_FILE_TITLE = "File kebutuhan"
    const val ORDER_DETAIL_RESULT_LABEL = "HASIL DARI PENYEDIA JASA"
    const val ORDER_DETAIL_RESULT_TITLE = "Hasil pekerjaan"
    const val ORDER_DETAIL_REVISION_LABEL = "CATATAN REVISI"
    const val ORDER_DETAIL_FILE_ACTION = "Buka file"

    // Order status contextual sentences (status x role)
    const val ORDER_STATUS_PENDING_BUYER = "Menunggu penyedia jasa menerima pesananmu."
    const val ORDER_STATUS_PENDING_SELLER = "Pesanan baru masuk. Terima untuk mulai mengerjakan."
    const val ORDER_STATUS_IN_PROGRESS_BUYER = "Penyedia jasa sedang mengerjakan pesananmu."
    const val ORDER_STATUS_IN_PROGRESS_SELLER = "Kerjakan lalu unggah hasilnya untuk pemesan."
    const val ORDER_STATUS_DELIVERED_BUYER = "Hasil sudah dikirim. Periksa dan konfirmasi bila sesuai."
    const val ORDER_STATUS_DELIVERED_SELLER = "Menunggu pemesan mengonfirmasi hasil."
    const val ORDER_STATUS_REVISION_BUYER = "Revisi sudah diminta. Menunggu penyedia jasa mengirim ulang hasil."
    const val ORDER_STATUS_REVISION_SELLER = "Pemesan meminta revisi. Periksa catatan lalu kirim hasil revisi."
    const val ORDER_STATUS_COMPLETED_BUYER = "Pesanan selesai. Lanjutkan simulasi pembayaran tanpa memproses uang asli."
    const val ORDER_STATUS_COMPLETED_SELLER = "Menunggu pemesan menjalankan simulasi pembayaran."
    const val ORDER_STATUS_PAID_BUYER = "Pesanan tuntas. Simulasi pembayaran selesai."
    const val ORDER_STATUS_PAID_SELLER = "Simulasi pembayaran selesai. Pesanan tuntas."
    const val ORDER_STATUS_CANCELLED = "Pesanan ini dibatalkan."
    const val ORDER_STATUS_REJECTED = "Pesanan ini ditolak penyedia jasa."
    const val ORDER_ACTION_CANCEL = "Batalkan"
    const val ORDER_ACTION_REJECT = "Tolak"
    const val ORDER_ACTION_ACCEPT = "Terima"
    const val ORDER_ACTION_UPLOAD_RESULT = "Unggah Hasil"
    const val ORDER_ACTION_UPLOAD_REVISION = "Kirim Revisi"
    const val ORDER_ACTION_CONFIRM_DONE = "Konfirmasi Selesai"
    const val ORDER_ACTION_REQUEST_REVISION = "Minta Revisi"
    const val ORDER_ACTION_SIMULATE_PAY = "Simulasi Bayar"
    const val ORDER_ACTION_WRITE_REVIEW = "Tulis Ulasan"
    const val ORDER_ACTION_WAITING_RESULT = "Menunggu hasil dari penyedia jasa..."
    const val ORDER_ACTION_WAITING_BUYER_CONFIRM = "Menunggu konfirmasi pemesan..."
    const val ORDER_ACTION_WAITING_REVISION = "Menunggu revisi dari penyedia jasa..."
    const val ORDER_ACTION_WAITING_PAYMENT = "Menunggu simulasi pembayaran dari pemesan..."
    const val ORDER_ACTION_SIMULATE_PAY_HELP = "Uji coba versi awal: tidak ada uang asli yang diproses. Ini pengganti sementara sebelum integrasi gerbang pembayaran seperti Midtrans."
    const val ORDER_REVISION_DIALOG_TITLE = "Minta Revisi"
    const val ORDER_REVISION_DIALOG_LABEL = "Catatan revisi"
    const val ORDER_REVISION_DIALOG_PLACEHOLDER = "Contoh: bagian grafik dibuat lebih kontras."
    const val ORDER_REVISION_DIALOG_CANCEL = "Batal"
    const val ORDER_REVISION_DIALOG_SUBMIT = "Kirim"
    const val ORDER_REVISION_NOTE_REQUIRED = "Catatan revisi tidak boleh kosong"

    // Chat section
    const val ORDER_CHAT_TITLE_PREFIX = "Chat dengan"
    const val ORDER_CHAT_EMPTY_TITLE = "Belum ada pesan"
    const val ORDER_CHAT_EMPTY_BODY_PREFIX = "Mulai percakapan dengan"
    const val ORDER_CHAT_INPUT_PLACEHOLDER = "Tulis pesan..."

    const val CREATE_ORDER_TITLE = "Konfirmasi Pesanan"
    const val CREATE_ORDER_NOTE_LABEL = "Catatan kebutuhan"
    const val CREATE_ORDER_NOTE_PLACEHOLDER = "Contoh: rapikan warna slide dan pertahankan isi utama."
    const val CREATE_ORDER_REQUIREMENT_FILE_TITLE = "File kebutuhan"
    const val CREATE_ORDER_REQUIREMENT_FILE_HELP = "Opsional, maksimal 20 MB. Unggah brief, data, atau referensi yang perlu dikerjakan."
    const val CREATE_ORDER_PICK_FILE = "Pilih file"
    const val CREATE_ORDER_CHANGE_FILE = "Ganti file"
    const val CREATE_ORDER_SELECTED_FILE = "File terpilih"
    const val CREATE_ORDER_SUBMIT = "Konfirmasi Pesanan"

    const val LOGIN_HEADLINE = "Halo,\nselamat datang."
    const val LOGIN_SUBHEADLINE = "Masuk untuk lanjut beri jasa, terima hasil."
    const val LOGIN_EMAIL_LABEL = "Email"
    const val LOGIN_EMAIL_PLACEHOLDER = "nama@email.com"
    const val LOGIN_PASSWORD_LABEL = "Password"
    const val LOGIN_PASSWORD_PLACEHOLDER = "••••••••"
    const val LOGIN_PASSWORD_HIDE = "Sembunyikan password"
    const val LOGIN_PASSWORD_SHOW = "Tampilkan password"
    const val LOGIN_SUBMIT = "Masuk"
    const val LOGIN_FORGOT_PASSWORD = "Lupa password?"
    const val LOGIN_OR = "atau"
    const val LOGIN_GOOGLE_MARK = "G"
    const val LOGIN_WITH_GOOGLE = "Lanjut dengan Google"
    const val LOGIN_GOOGLE_UNAVAILABLE = "Google Sign-In belum tersedia. Pastikan Play Services aktif."
    const val LOGIN_GOOGLE_CANCELLED = "Masuk dengan Google dibatalkan."
    const val LOGIN_GOOGLE_INVALID = "Token Google tidak valid. Silakan coba lagi."
    const val LOGIN_REGISTER_PREFIX = "Belum punya akun?"
    const val LOGIN_REGISTER_ACTION = "Buat sekarang"

    const val REGISTER_HEADLINE = "Buat\nakun baru."
    const val REGISTER_SUBHEADLINE = "Daftar dan mulai tawarkan jasamu."

    const val BACK_CONTENT_DESCRIPTION = "Kembali"

    const val REVIEW_TITLE = "Tulis Ulasan"

    const val HOME_GREETING_NAMED = "Halo, %s"
    const val HOME_GREETING_GENERIC = "Halo"
    const val HOME_SUBTITLE = "Mau tugas apa yang dituntaskan hari ini?"
    const val HOME_SECTION_FEATURED = "Sedang ramai"
    const val HOME_SECTION_FEATURED_SUB = "Paling banyak dipesan minggu ini"
    const val HOME_SECTION_LATEST = "Terbaru"
    const val HOME_EMPTY_TITLE = "Belum ada layanan"
    const val HOME_EMPTY_BODY = "Coba kategori lain atau kembali nanti."

    const val SEARCH_NO_RESULTS_TITLE_QUERY = "Tidak ada hasil untuk"

    // Profile
    const val PROFILE_TITLE = "Profil"
    const val PROFILE_LOGOUT = "Keluar"
    const val PROFILE_EDIT = "Edit Profil"
    const val PROFILE_ADD_LISTING = "Tambah Layanan Baru"
    const val PROFILE_MY_LISTINGS = "Layanan Saya"
    const val PROFILE_PORTFOLIO_TITLE = "Portofolio"
    const val PROFILE_PORTFOLIO_ACTION = "Kelola"
    const val PROFILE_PORTFOLIO_EMPTY = "Tambahkan contoh karya agar calon pemesan lebih yakin."
    const val PROFILE_NOT_FOUND = "Profil tidak ditemukan"
    const val PROFILE_STAT_RATING = "RATING"
    const val PROFILE_STAT_COMPLETED_ORDERS = "PESANAN SELESAI"
    const val PROFILE_LISTING_COUNT_LABEL = "LAYANAN"
    const val PROFILE_EMPTY_LISTINGS_TITLE = "Belum ada layanan"
    const val PROFILE_EMPTY_LISTINGS_BODY = "Tawarkan jasamu, mulai dari layanan pertama."
    const val PROFILE_VERIFICATION_TITLE = "Pusat Verifikasi"
    const val PROFILE_VERIFICATION_BODY = "Identitas %s · Keahlian %s"
    const val PROFILE_VERIFICATION_IDENTITY = "Identitas: %s"
    const val PROFILE_VERIFICATION_SKILL = "Keahlian: %s"
    const val PROFILE_VERIFICATION_ACTION = "Lihat status"
    const val ROLE_BUYER = "Pemesan"
    const val ROLE_SELLER = "Penyedia Jasa"
    const val ROLE_BOTH = "Keduanya"

    // Public badges
    const val BADGE_IDENTITY = "Identitas"
    const val BADGE_SKILL = "Ahli %s"
    const val BADGE_SKILL_COMPACT = "Ahli %s"

    // Portfolio
    const val PORTFOLIO_TITLE = "Portofolio"
    const val PORTFOLIO_ADD = "Tambah Portofolio"
    const val PORTFOLIO_LIST_TITLE = "Karya Kamu"
    const val PORTFOLIO_FORM_CREATE_TITLE = "Portofolio Baru"
    const val PORTFOLIO_FORM_EDIT_TITLE = "Edit Portofolio"
    const val PORTFOLIO_FIELD_TITLE = "Judul karya"
    const val PORTFOLIO_TITLE_PLACEHOLDER = "Contoh: Poster acara UKM"
    const val PORTFOLIO_FIELD_CATEGORY = "Kategori"
    const val PORTFOLIO_FIELD_DESCRIPTION = "Deskripsi"
    const val PORTFOLIO_DESCRIPTION_PLACEHOLDER = "Ceritakan konteks, peranmu, dan hasilnya"
    const val PORTFOLIO_FIELD_LINK = "Tautan eksternal (opsional)"
    const val PORTFOLIO_LINK_PLACEHOLDER = "https://..."
    const val PORTFOLIO_IMAGE_TITLE = "Gambar portofolio"
    const val PORTFOLIO_IMAGE_HELP = "Opsional, maksimal 5 MB."
    const val PORTFOLIO_IMAGE_EMPTY = "Belum ada gambar"
    const val PORTFOLIO_IMAGE_ATTACHED = "Gambar terpasang"
    const val PORTFOLIO_PICK_IMAGE = "Pilih gambar"
    const val PORTFOLIO_CHANGE_IMAGE = "Ganti gambar"
    const val PORTFOLIO_REMOVE_IMAGE = "Hapus gambar"
    const val PORTFOLIO_SAVE = "Simpan"
    const val PORTFOLIO_CANCEL = "Batal"
    const val PORTFOLIO_EDIT = "Edit portofolio"
    const val PORTFOLIO_DELETE = "Hapus"
    const val PORTFOLIO_DELETE_TITLE = "Hapus portofolio?"
    const val PORTFOLIO_DELETE_BODY = "Item ini akan dihapus dari profil publikmu."
    const val PORTFOLIO_DELETE_CONFIRM = "Hapus"
    const val PORTFOLIO_DELETE_CANCEL = "Batal"
    const val PORTFOLIO_EMPTY_MANAGE = "Belum ada portofolio. Tambahkan karya terbaikmu dari tombol di atas."
    const val PORTFOLIO_EMPTY_PUBLIC = "Belum ada portofolio publik."
    const val PORTFOLIO_OPEN_LINK = "Buka tautan"
    const val PORTFOLIO_CREATE_SUCCESS = "Portofolio ditambahkan"
    const val PORTFOLIO_UPDATE_SUCCESS = "Portofolio diperbarui"
    const val PORTFOLIO_DELETE_SUCCESS = "Portofolio dihapus"
    const val PORTFOLIO_ERROR_LOGIN_REQUIRED = "Masuk kembali untuk mengelola portofolio"
    const val PORTFOLIO_ERROR_TITLE_REQUIRED = "Judul portofolio tidak boleh kosong"
    const val PORTFOLIO_ERROR_DESCRIPTION_REQUIRED = "Deskripsi portofolio tidak boleh kosong"
    const val PORTFOLIO_ERROR_LINK_INVALID = "Gunakan tautan yang diawali http:// atau https://"

    // Verification
    const val VERIFICATION_TITLE = "Pusat Verifikasi"
    const val VERIFICATION_SUBTITLE = "Verifikasi opsional untuk membangun kepercayaan saat menawarkan layanan."
    const val VERIFICATION_IDENTITY_TITLE = "Verifikasi Identitas"
    const val VERIFICATION_IDENTITY_BODY = "KTM ditinjau manual melalui Firebase Console."
    const val VERIFICATION_SKILL_TITLE = "Verifikasi Keahlian"
    const val VERIFICATION_SKILL_BODY = "Badge keahlian mengikuti kategori Akademik, Desain, dan Data."
    const val VERIFICATION_STATUS_LABEL = "STATUS"
    const val VERIFICATION_STATUS_NOT_SUBMITTED = "Belum diajukan"
    const val VERIFICATION_STATUS_PENDING = "Menunggu review"
    const val VERIFICATION_STATUS_APPROVED = "Disetujui"
    const val VERIFICATION_STATUS_REJECTED = "Ditolak"
    const val VERIFICATION_SKILL_NONE = "Belum ada badge"
    const val VERIFICATION_SKILL_ACTIVE = "%d badge aktif"
    const val VERIFICATION_ACTION_SUBMIT = "Ajukan Verifikasi"
    const val VERIFICATION_ACTION_VIEW_STATUS = "Lihat Status"
    const val VERIFICATION_ACTION_RESUBMIT = "Ajukan Ulang"
    const val VERIFICATION_REJECTION_LABEL = "ALASAN PENOLAKAN"
    const val VERIFICATION_REJECTION_FALLBACK = "Admin belum menambahkan alasan penolakan."
    const val VERIFICATION_APPROVED_BADGE = "Badge aktif"
    const val VERIFICATION_ERROR_LOGIN_REQUIRED = "Masuk kembali untuk mengajukan verifikasi"
    const val VERIFICATION_ERROR_PENDING_DUPLICATE = "Pengajuan sedang menunggu review"
    const val VERIFICATION_ERROR_ALREADY_APPROVED = "Verifikasi ini sudah disetujui"

    // Identity verification
    const val IDENTITY_TITLE = "Verifikasi Identitas"
    const val IDENTITY_STATUS_BODY = "KTM kamu ditinjau manual oleh admin. Verifikasi tetap opsional."
    const val IDENTITY_UPLOAD_TITLE = "KTM Mahasiswa"
    const val IDENTITY_UPLOAD_BODY = "Unggah foto atau PDF KTM. File disimpan privat dan tidak muncul di profil publik."
    const val IDENTITY_PICK_FILE = "Pilih File KTM"
    const val IDENTITY_CHANGE_FILE = "Ganti File"
    const val IDENTITY_SELECTED_FILE = "File terpilih"
    const val IDENTITY_NOTE_LABEL = "Catatan untuk admin (opsional)"
    const val IDENTITY_NOTE_PLACEHOLDER = "Contoh: KTM semester ini belum dicetak ulang"
    const val IDENTITY_SUBMIT = "Kirim Pengajuan"
    const val IDENTITY_SUBMIT_SUCCESS = "Pengajuan identitas dikirim"
    const val IDENTITY_ERROR_FILE_REQUIRED = "Pilih file KTM terlebih dahulu"

    // Skill verification
    const val SKILL_TITLE = "Verifikasi Keahlian"
    const val SKILL_STATUS_BODY = "Ajukan bukti keahlian sesuai kategori Berima."
    const val SKILL_SECTION_CATEGORY = "Kategori Keahlian"
    const val SKILL_SECTION_PORTFOLIO = "Portofolio"
    const val SKILL_PORTFOLIO_NONE = "Tanpa portofolio"
    const val SKILL_PORTFOLIO_EMPTY = "Belum ada portofolio untuk kategori ini."
    const val SKILL_LINK_LABEL = "Tautan bukti (opsional)"
    const val SKILL_LINK_PLACEHOLDER = "https://..."
    const val SKILL_FILE_TITLE = "File bukti tambahan"
    const val SKILL_FILE_BODY = "Opsional. Sertifikat, screenshot hasil kerja, atau dokumen pendukung."
    const val SKILL_PICK_FILE = "Pilih File Bukti"
    const val SKILL_CHANGE_FILE = "Ganti File"
    const val SKILL_SUBMIT = "Kirim Pengajuan"
    const val SKILL_SUBMIT_SUCCESS = "Pengajuan keahlian dikirim"
    const val SKILL_ERROR_EVIDENCE_REQUIRED = "Tambahkan minimal satu bukti keahlian"
    const val SKILL_ERROR_LINK_INVALID = "Gunakan tautan yang diawali http:// atau https://"

    // Edit profile
    const val EDIT_PROFILE_TITLE = "Edit Profil"
    const val EDIT_PROFILE_CHANGE_PHOTO = "Ubah Foto"
    const val EDIT_PROFILE_SECTION_PUBLIC = "Informasi Publik"
    const val EDIT_PROFILE_SECTION_ROLE = "Peran di Berima"
    const val EDIT_PROFILE_FIELD_NAME = "Nama"
    const val EDIT_PROFILE_FIELD_BIO = "Bio"
    const val EDIT_PROFILE_BIO_PLACEHOLDER = "Ceritakan sedikit tentang dirimu"
    const val EDIT_PROFILE_FIELD_FACULTY = "Fakultas"
    const val EDIT_PROFILE_FACULTY_PLACEHOLDER = "Contoh: Teknik Informatika"
    const val EDIT_PROFILE_ROLE_LABEL = "Peran"
    const val EDIT_PROFILE_ROLE_HELP = "Pilih bagaimana kamu memakai Berima."
    const val EDIT_PROFILE_SAVE = "Simpan Perubahan"

    // Listing form (Create + Edit)
    const val LISTING_CREATE_TITLE = "Buat Layanan"
    const val LISTING_EDIT_TITLE = "Edit Layanan"
    const val LISTING_SECTION_DETAIL = "Detail Layanan"
    const val LISTING_SECTION_PRICING = "Harga & Waktu"
    const val LISTING_SECTION_EXTRA = "Tambahan"
    const val LISTING_FIELD_TITLE = "Judul"
    const val LISTING_TITLE_PLACEHOLDER = "Contoh: Desain poster acara kampus"
    const val LISTING_FIELD_CATEGORY = "Kategori"
    const val LISTING_FIELD_DESCRIPTION = "Deskripsi"
    const val LISTING_DESCRIPTION_PLACEHOLDER = "Jelaskan layanan yang kamu tawarkan"
    const val LISTING_FIELD_PRICE = "Harga"
    const val LISTING_PRICE_PLACEHOLDER = "0"
    const val LISTING_FIELD_DELIVERY = "Waktu pengerjaan"
    const val LISTING_DELIVERY_PLACEHOLDER = "Maks. 48"
    const val LISTING_DELIVERY_UNIT = "jam"
    const val LISTING_FIELD_TAGS = "Tags (opsional)"
    const val LISTING_TAGS_PLACEHOLDER = "Pisahkan dengan koma: desain, logo"
    const val LISTING_IMAGE_TITLE = "Gambar Layanan"
    const val LISTING_IMAGE_HELP = "Opsional, maksimal 5 MB. Gambar akan tampil di kartu dan detail layanan."
    const val LISTING_IMAGE_EMPTY = "Belum ada gambar"
    const val LISTING_IMAGE_ATTACHED = "Gambar terpasang"
    const val LISTING_PICK_IMAGE = "Pilih gambar"
    const val LISTING_CHANGE_IMAGE = "Ganti gambar"
    const val LISTING_REMOVE_IMAGE = "Hapus gambar"
    const val LISTING_SAVE_CREATE = "Simpan Layanan"
    const val LISTING_SAVE_EDIT = "Simpan Perubahan"
    const val LISTING_PRICE_PREVIEW_PREFIX = "Pemesan membayar"
    const val LISTING_DELIVERY_HINT_PREFIX = "Maksimal"
    const val LISTING_DELIVERY_HINT_SUFFIX = "jam"
    const val LISTING_POLICY_TITLE = "Kebijakan layanan"
    const val LISTING_POLICY_BODY = "Saya menyatakan layanan ini bukan joki tugas/ujian, plagiarisme, pembuatan skripsi atau karya ilmiah atas nama orang lain, pemalsuan dokumen, atau aktivitas ilegal."
    const val LISTING_POLICY_ERROR = "Setujui kebijakan layanan Berima terlebih dahulu"
    const val LISTING_INACTIVE_LABEL = "NONAKTIF"
    const val LISTING_INACTIVE_BODY = "Layanan ini sedang nonaktif dan tidak muncul di marketplace."
    const val LISTING_DEACTIVATE = "Nonaktifkan layanan"
    const val LISTING_DEACTIVATE_SHORT = "Nonaktifkan"
    const val LISTING_DEACTIVATE_TITLE = "Nonaktifkan layanan?"
    const val LISTING_DEACTIVATE_BODY = "Layanan tidak akan muncul di Beranda, Pencarian, atau profil publik. Kamu tetap bisa melihatnya dari Profil."
    const val LISTING_DEACTIVATE_CONFIRM = "Nonaktifkan"
    const val LISTING_DEACTIVATE_CANCEL = "Batal"
    const val LISTING_DEACTIVATE_SUCCESS = "Layanan dinonaktifkan"
    const val LISTING_EDIT_ACTION = "Edit Layanan"
    const val LISTING_ORDER_ACTION = "Pesan Sekarang"
    const val LISTING_NOT_FOUND = "Layanan tidak ditemukan."
    const val LISTING_ESTIMATE_PREFIX = "Estimasi selesai:"
    const val LISTING_SELLER_PROFILE_ACTION = "Lihat profil"
    const val LISTING_SELLER_NO_RATING = "Belum ada rating"
    const val LISTING_SELLER_ORDER_COUNT = "%d pesanan"
    const val LISTING_REVIEWS_TITLE = "Ulasan"

    // Review
    const val REVIEW_NOT_FOUND = "Pesanan tidak ditemukan."
    const val REVIEW_RATING_LABEL = "Rating"
    const val REVIEW_COMMENT_LABEL = "Komentar (opsional)"
    const val REVIEW_SUBMIT = "Kirim Ulasan"
    const val REVIEW_STAR_DESCRIPTION = "Rating %d"

    const val PROFILE_PHOTO_DESCRIPTION = "Foto profil"

    // Category picker (shared)
    const val CATEGORY_SHEET_TITLE = "Pilih Kategori"
    const val CATEGORY_ACADEMIC = "Dukungan Akademik"
    const val CATEGORY_VISUAL = "Branding Visual"
    const val CATEGORY_DATA = "Pengolahan Data"
}
